Get raw text data from xlsx

In [ ]:
import pandas as pd

txt=pd.read_excel('111.xlsx',index_col=None)

FileNotFoundError: ignored

In [ ]:
import pandas as pd

txt=pd.read_excel('Book1.xlsx',index_col=None)

In [ ]:
lis=['2022001P_02_02282022']


xls = pd.ExcelFile('111.xlsx')
df1 = pd.read_excel(xls, 'Sheet1')

In [ ]:
df1 = txt

In [ ]:
### 2:speaker   3:text    4:label

print(df1.iloc[:,1])

0                                      How was your day?
1                                      How was your day?
2                                         There's pizza.
3                 Don't mind bringing the chicken wings.
4                                                Shrimp.
                             ...                        
753                      You have to do it consistently.
754                                        Are you sure?
755    Because I'm going to email her and verify beca...
756                          And that's reading or math?
757                              What about the reading?
Name: autotransricpt, Length: 758, dtype: object


In [ ]:
import pickle
sentence=[]
label=[]
strname='collect.pkl'
label_parent=['UP','LP','RF','BD','IQ','DQ','IC','DC','NTA','TA','AN','NA']
label_kid=[]

for k in lis:
  df = pd.read_excel(xls, k)

  for i in range(len(df)):
    if df.iloc[i,4] in res:
    #print(df.iloc[i,3])
    #print(df.iloc[i,4])
      sentence.append(df.iloc[i,3])
      label.append(res.index(df.iloc[i,4]))

with open(strname, 'wb') as fp:
  pickle.dump([sentence, label],fp)


In [ ]:
import pickle
sentence=[]
label=[]
strname='collect.pkl'
label_parent=['UP','LP','RF','BD','IQ','DQ','IC','DC','NTA','TA','AN','NA']
label_kid=[]


for i in range(len(df1)):
    if df1.iloc[i,2] in label_parent:
    #print(df.iloc[i,3])
    #print(df.iloc[i,4])
      sentence.append(df1.iloc[i,1])
      label.append(label_parent.index(df1.iloc[i,2]))

with open(strname, 'wb') as fp:
  pickle.dump([sentence, label],fp)
  print(label)

[4, 7, 5, 7, 5, 7, 6, 8, 4, 7, 7, 5, 5, 9, 9, 7, 7, 8, 5, 9, 7, 4, 6, 4, 5, 7, 5, 5, 9, 9, 9, 5, 0, 5, 1, 9, 0, 5, 9, 9, 9, 1, 9, 9, 9, 7, 4, 5, 5, 9, 9, 8, 9, 8, 1, 5, 5, 5, 9, 9, 9, 9, 6, 8, 6, 9, 5, 6, 9, 7, 6, 7, 6, 9, 7, 7, 7, 8, 6, 9, 7, 7, 7, 9, 5, 7, 1, 7, 9, 1, 7, 7, 9, 9, 9, 4, 5, 9, 9, 9, 9, 6, 9, 7, 0, 1, 9, 5, 7, 5, 5, 6, 6, 5, 9, 1, 7, 1, 9, 8, 9, 0, 0, 9, 9, 6, 9, 0, 0, 0, 7, 7, 6, 7, 1, 0, 4, 5, 8, 5, 8, 8, 7, 7, 7, 9, 9, 9, 9, 7, 7, 1, 9, 7, 9, 9, 9, 7, 0, 9, 5, 9, 9, 5, 1, 5, 5, 9, 9, 4, 9, 9, 7, 4, 8, 9, 9, 9, 9, 9, 9, 4, 6, 9, 4, 6, 1, 9, 4, 8, 6, 5, 9, 6, 9, 7, 7, 7, 5, 8, 4, 7, 7, 5, 8, 4, 7, 6, 7, 7, 4, 9, 8, 7, 4, 9, 9, 9, 9, 7, 2, 5, 9, 9, 7, 8, 0, 9, 6, 7, 0, 0, 0, 9, 4, 9, 9, 9, 0, 9, 0, 9, 0, 1, 5, 5, 5, 7, 9, 9, 9, 6, 7, 9, 5, 1, 8, 2, 9, 9, 9, 9, 6, 9, 9, 0, 0, 1, 5, 7, 5, 5, 4, 9, 7, 1, 0, 9, 5, 8, 1, 0, 9, 6, 5, 9, 9, 9, 9, 7, 9, 5, 0, 6, 5, 5, 5, 9, 0, 7, 9, 9, 5, 0, 5, 1, 9, 0, 5, 9, 9, 6, 9, 1, 9, 9, 8, 9, 7, 9, 7, 5, 5, 5, 8, 4, 8, 7, 5, 9, 9, 4, 5, 

In [ ]:
print(label[720:725])

[6, 6, 6, 9, 7]


end


In [ ]:
lis=['2022001P_02_02282022','2022001P_05_03032022','2022001C_02_02282022','2022001C_05_03032022','2022002P_05_03162022','2022002P_02_03112022','2022002C_02_03112022','2022002C_05_03162022','2022003P_02_20220403','2022004C_01_20220408','2022004P_01_20220408','2022003C_05_20220411','2022004P_04_20220414']


xls = pd.ExcelFile('111.xlsx')
df1 = pd.read_excel(xls, '2022001P_02_02282022')

In [ ]:
import pickle
clips_sentence, clips_label = pickle.load(open('clip2test.pkl', 'rb'))

FileNotFoundError: ignored

In [ ]:
with open('Fruits.pkl', 'wb') as fp:
  pickle.dump([clips_sentence, clips_label],fp)

In [ ]:

import pickle
clips_sentence, clips_label = pickle.load(open('Fruits.pkl', 'rb'))


In [ ]:
import pickle
sentence=[]
label=[]


for k in lis:
  df = pd.read_excel(xls, k)
  sentence=[]
  label=[]
  strname=k+'.pkl'
  for i in range(len(df)):
    print(txt.iloc[i,3])
    print(txt.iloc[i,4])
    #sentence.append(df.iloc[i,2])
    #label.append(0)

  #with open(strname, 'wb') as fp:
    #pickle.dump([sentence, label],fp)



In [ ]:
import pickle
sentence=[]
label=[]
strname='collect.pkl'
res=['UP','LP','RF','BD','IQ','DQ','IC','DC','NTA','TA']

for k in lis:
  df = pd.read_excel(xls, k)

  for i in range(len(df)):
    if df.iloc[i,4] in res:
    #print(df.iloc[i,3])
    #print(df.iloc[i,4])
      sentence.append(df.iloc[i,3])
      label.append(res.index(df.iloc[i,4]))

with open(strname, 'wb') as fp:
  pickle.dump([sentence, label],fp)



In [ ]:
with open('test1.pkl', 'wb') as fp:
  pickle.dump([sentence, label],fp)

In [ ]:
lis=['2022001P_02_02282022','2022001P_05_03032022','2022001C_02_02282022','2022001C_05_03032022','2022002P_05_03162022','2022002P_02_03112022','2022002C_02_03112022','2022002C_05_03162022','2022003P_02_20220403','2022004C_01_20220408','2022004P_01_20220408','2022003C_05_20220411','2022004P_04_20220414']


xls = pd.ExcelFile('111.xlsx')
df1 = pd.read_excel(xls, '2022001P_05_03032022')

In [ ]:
res=['UP','LP','RF','BD','IQ','DQ','IC','DC','NTA','TA']

for i in range(len(df1)):
  print(df1.iloc[i,3])
  if df1.iloc[i,4] in res:
    print(df1.iloc[i,4])
    print(res.index(df1.iloc[i,4]))
    if df1.iloc[i,2]!='Mom':
      print(1)
  #print((df1.iloc[i,2]))



Did you press the camera?
DQ
5
1
Yeah, but it hasn't even loaded yet
So how was your day?
IQ
4
1
It was good.
Did you do your project?
DQ
5
1
Yeah. I was continuing on that project today in 4th period
And that's the one that the pictures is due?
DQ
5
1
And what about the-
The zoo project?
Uh huh
He was gonna call me, because like his phone wasn't working, but supposably like his dad got him the new iphone and then his phone just like shut down.
So he had his phone fixed yesterday, so he said he was gonna call me.
Where's my headphones?
IQ
4
1
Which ones?
The ones that go to my iPad.
I was looking for them, I couldn't find them.
They was in your room the last time I saw them
Exactly. But now no one knows where there.
And when I use them, I put them back in the room;
So, maybe one of the kids used them, or- 
Alright, so you got to do iReady
IC
6
1
I know
Reading and math.
IC
6
1
Just Math
Yeah, just Math.
I did start a lesson, but then I failed the lesson cause I didn't understand. 
But,

In [ ]:
sentence, label=pickle.load(open('2022001P_05_03032022.pkl', 'rb'))

In [ ]:
a_file = open("111.txt", 'r+')
file_contents = a_file.read()# a_file = open("Interaction_Lab_2022008C_20220512.txt", 'r+')
#file_contents = a_file.read()
print(file_contents)

1
2
3 
4



In [ ]:
from moviepy.video.io.ffmpeg_tools import ffmpeg_extract_subclip

required_video_file = "video456.mp4"

#with open("times.txt") as f:
  #times = f.readlines()

#times = [x.strip() for x in times]

#for time in times:
  #starttime = int(time.split("-")[0])
  #endtime = int(time.split("-")[1])
  #ffmpeg_extract_subclip(required_video_file, starttime, endtime, targetname=str(times.index(time)+1)+".mp4")

starttime = 0.5*60
endtime = 1.5*60
ffmpeg_extract_subclip(required_video_file, starttime, endtime, targetname="output123.mp4")





[MoviePy] Running:
>>> /usr/local/lib/python3.7/dist-packages/imageio_ffmpeg/binaries/ffmpeg-linux64-v4.2.2 -y -i video456.mp4 -ss 30.00 -t 60.00 -vcodec copy -acodec copy output123.mp4
... command successful.


In [ ]:
from moviepy.video.io.ffmpeg_tools import ffmpeg_extract_subclip

import pandas as pd
required_video_file = "video456.mp4"


time_start = [1150,4150,5854,12440,13196]
time_end=[2660,5818,12270,13062,17130]

for time in range(len(time_start)):
  strname="tp"+str(time)+".mp4"
  ffmpeg_extract_subclip(required_video_file, time_start[i], time_end[i], targetname=strname)

#starttime = 0.5*60
#endtime = 1.5*60
#ffmpeg_extract_subclip(required_video_file, starttime, endtime, targetname="output123.mp4")




[MoviePy] Running:
>>> /usr/local/lib/python3.7/dist-packages/imageio_ffmpeg/binaries/ffmpeg-linux64-v4.2.2 -y -i video456.mp4 -ss 1150.00 -t 1510.00 -vcodec copy -acodec copy tp0.mp4
... command successful.

[MoviePy] Running:
>>> /usr/local/lib/python3.7/dist-packages/imageio_ffmpeg/binaries/ffmpeg-linux64-v4.2.2 -y -i video456.mp4 -ss 1150.00 -t 1510.00 -vcodec copy -acodec copy tp1.mp4
... command successful.

[MoviePy] Running:
>>> /usr/local/lib/python3.7/dist-packages/imageio_ffmpeg/binaries/ffmpeg-linux64-v4.2.2 -y -i video456.mp4 -ss 1150.00 -t 1510.00 -vcodec copy -acodec copy tp2.mp4
... command successful.

[MoviePy] Running:
>>> /usr/local/lib/python3.7/dist-packages/imageio_ffmpeg/binaries/ffmpeg-linux64-v4.2.2 -y -i video456.mp4 -ss 1150.00 -t 1510.00 -vcodec copy -acodec copy tp3.mp4
... command successful.

[MoviePy] Running:
>>> /usr/local/lib/python3.7/dist-packages/imageio_ffmpeg/binaries/ffmpeg-linux64-v4.2.2 -y -i video456.mp4 -ss 1150.00 -t 1510.00 -vcodec copy 

In [ ]:
!pip install imageio-ffmpeg

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 26.9 MB 84.1 MB/s 


In [ ]:
lis=['2022001P_02_02282022']


xls = pd.ExcelFile('tep.xlsx')
df1 = pd.read_excel(xls, 'tep')


In [ ]:
dic={"neutral":0,
     "angry":1,
     "sad":2,
     "fear":3,
     "ps":4,
     "happy":5,
     "disgust":6}

import numpy as np

res=np.zeros((7,7),dtype=np.int)

for i in range(len(df1)):
  #print(i)
  res[dic[df1.iloc[i,1]],dic[df1.iloc[i,2]]]=res[dic[df1.iloc[i,1]],dic[df1.iloc[i,2]]]+1

print(len(df1))
xls = pd.ExcelFile('tep001.xlsx')
df1 = pd.read_excel(xls, 'tep001')

for i in range(len(df1)):
  #print(i)
  res[dic[df1.iloc[i,1]],dic[df1.iloc[i,2]]]=res[dic[df1.iloc[i,1]],dic[df1.iloc[i,2]]]+1

print(len(df1))
xls = pd.ExcelFile('tep002.xlsx')
df1 = pd.read_excel(xls, 'tep002')

for i in range(len(df1)):
  #print(i)
  res[dic[df1.iloc[i,1]],dic[df1.iloc[i,2]]]=res[dic[df1.iloc[i,1]],dic[df1.iloc[i,2]]]+1

print(len(df1))
print(res)
print(res[:,0])

<ipython-input-15-29c5b3e5bb5c>:11: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  res=np.zeros((7,7),dtype=np.int)


467
958
1479
[[1563   20    0    5   15   13    3]
 [  35    7    0    6    2    3    0]
 [ 120    1   56    8    3    1    0]
 [ 291    3    0  265    9    0    0]
 [ 178    2    1   11  123    0    2]
 [  86    1    1    3    0   35    0]
 [  20    0    0    0    1    0   11]]
[1563   35  120  291  178   86   20]


In [ ]:
print(sum(res[:,0]))

2293


In [ ]:
dic={"neutral":0,
     "angry":1,
     "sad":2,
     "fear":3,
     "ps":4,
     "happy":5,
     "disgust":6,
     "surprise":4,
     "neutral/surprise":0}

import numpy as np
import pandas as pd
res1=np.zeros((7,7),dtype=np.int)
res2=np.zeros((7,7),dtype=np.int)
xls = pd.ExcelFile('002family.xlsx')
df1 = pd.read_excel(xls, 'Sheet1')
print(df1.iloc[0,:])
print(df1.iloc[0,3])
print(df1.iloc[0,9])
print(df1.iloc[0,1][-5])

for i in range(len(df1)):
  #print(i)
  #if df1.iloc[i,1][-5]=='B' or df1.iloc[i,1][-5]=='b' or df1.iloc[i,1][-5]=='G' or df1.iloc[i,1][-5]=='g':
  #  res2[dic[df1.iloc[i,1]],dic[df1.iloc[i,2]]]=res2[dic[df1.iloc[i,1]],dic[df1.iloc[i,2]]]+1
  #else:
  #  res1[dic[df1.iloc[i,1]],dic[df1.iloc[i,2]]]=res1[dic[df1.iloc[i,1]],dic[df1.iloc[i,2]]]+1
  if df1.iloc[i,11]==1:
    continue
  if df1.iloc[i,1][-5]=='f' or df1.iloc[i,1][-5]=='F' or df1.iloc[i,1][-5]=='M' or df1.iloc[i,1][-5]=='m':
    res2[dic[df1.iloc[i,3]],dic[df1.iloc[i,9]]]=res2[dic[df1.iloc[i,3]],dic[df1.iloc[i,9]]]+1
  else:
    res1[dic[df1.iloc[i,3]],dic[df1.iloc[i,9]]]=res1[dic[df1.iloc[i,3]],dic[df1.iloc[i,9]]]+1



print(len(df1))
print(res1)
print(sum(res1))
print(res2)
print(sum(res2))

<ipython-input-1-1594ddbfd9b3>:13: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  res1=np.zeros((7,7),dtype=np.int)
<ipython-input-1-1594ddbfd9b3>:14: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for mo

Unnamed: 0                              0
0             2022002C0103102022_101g.wav
1                                 neutral
GT                                neutral
DB                                   fear
sa                                  angry
ra                                   fear
iemo                                angry
Unnamed: 8                            NaN
sa2                               neutral
Name: 0, dtype: object
neutral
neutral
g


IndexError: ignored

In [ ]:
dic={"neutral":0,
     "angry":1,
     "sad":2,
     "fear":3,
     "ps":4,
     "happy":5,
     "disgust":6,
     "surprise":4,
     "neutral/surprise":0}

import numpy as np
import pandas as pd
res1=np.zeros((7,7),dtype=np.int)
res2=np.zeros((7,7),dtype=np.int)
xls = pd.ExcelFile('001family.xlsx')
df1 = pd.read_excel(xls, 'Sheet1')
print(df1.iloc[0,:])
print(df1.iloc[0,3])
print(df1.iloc[0,9])
print(df1.iloc[0,1][-5])

for i in range(len(df1)):
  #print(i)
  #if df1.iloc[i,1][-5]=='B' or df1.iloc[i,1][-5]=='b' or df1.iloc[i,1][-5]=='G' or df1.iloc[i,1][-5]=='g':
  #  res2[dic[df1.iloc[i,1]],dic[df1.iloc[i,2]]]=res2[dic[df1.iloc[i,1]],dic[df1.iloc[i,2]]]+1
  #else:
  #  res1[dic[df1.iloc[i,1]],dic[df1.iloc[i,2]]]=res1[dic[df1.iloc[i,1]],dic[df1.iloc[i,2]]]+1
  #if df1.iloc[i,11]=='1':
    #continue
  if df1.iloc[i,1][-5]=='f' or df1.iloc[i,1][-5]=='F' or df1.iloc[i,1][-5]=='M' or df1.iloc[i,1][-5]=='m':
    res2[dic[df1.iloc[i,3]],dic[df1.iloc[i,9]]]=res2[dic[df1.iloc[i,3]],dic[df1.iloc[i,9]]]+1
  else:
    res1[dic[df1.iloc[i,3]],dic[df1.iloc[i,9]]]=res1[dic[df1.iloc[i,3]],dic[df1.iloc[i,9]]]+1



print(len(df1))
print(res1)
print(sum(res1))
print(res2)
print(sum(res2))

<ipython-input-7-f87ed85e5ab9>:13: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  res1=np.zeros((7,7),dtype=np.int)
<ipython-input-7-f87ed85e5ab9>:14: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for mo

Unnamed: 0                              0
0              2022001C0102262022_0_f.wav
1                                     sad
GT                                neutral
DB                                  happy
sa                               surprise
ra                                  angry
iemo                                angry
Unnamed: 8                            NaN
sa.1                              neutral
Unnamed: 10                           NaN
Unnamed: 11                           NaN
Name: 0, dtype: object
neutral
neutral
f
949
[[148  45   0   0  41  72   0]
 [  1   2   0   0   2   0   0]
 [  7   1   0   0   0   0   0]
 [ 41   5   0   0   2  36   2]
 [ 11   6   0   0   1  21   0]
 [  3   0   0   0   1   3   0]
 [  5   3   0   0   1   0   0]]
[216  62   0   0  48 132   2]
[[203  52   0   0  31 110   0]
 [  2   3   0   1   5   1   0]
 [  2   0   0   0   0   2   0]
 [ 14   1   0   1   0  18   0]
 [ 14   7   0   0   0  12   0]
 [  4   3   0   0   0   2   0]
 [  0   0   0   0

In [ ]:
dic={"neutral":0,
     "angry":1,
     "sad":2,
     "fear":3,
     "ps":4,
     "happy":5,
     "disgust":6,
     "surprise":4,
     "neutral/surprise":0}

import numpy as np
import pandas as pd
res1=np.zeros((7,7),dtype=np.int)
res2=np.zeros((7,7),dtype=np.int)
xls = pd.ExcelFile('003family_1.xlsx')
df1 = pd.read_excel(xls, 'Sheet1')
print(df1.iloc[0,:])
print(df1.iloc[0,5])
print(df1.iloc[0,9])
print(df1.iloc[0,1][-5])

for i in range(len(df1)):
  #print(i)
  #if df1.iloc[i,1][-5]=='B' or df1.iloc[i,1][-5]=='b' or df1.iloc[i,1][-5]=='G' or df1.iloc[i,1][-5]=='g':
  #  res2[dic[df1.iloc[i,1]],dic[df1.iloc[i,2]]]=res2[dic[df1.iloc[i,1]],dic[df1.iloc[i,2]]]+1
  #else:
  #  res1[dic[df1.iloc[i,1]],dic[df1.iloc[i,2]]]=res1[dic[df1.iloc[i,1]],dic[df1.iloc[i,2]]]+1
  if df1.iloc[i,11]=='1':
    continue
  if df1.iloc[i,1][-5]=='f' or df1.iloc[i,1][-5]=='F' or df1.iloc[i,1][-5]=='M' or df1.iloc[i,1][-5]=='m':
    res2[dic[df1.iloc[i,9]],dic[df1.iloc[i,5]]]=res2[dic[df1.iloc[i,9]],dic[df1.iloc[i,5]]]+1
  else:
    res1[dic[df1.iloc[i,9]],dic[df1.iloc[i,5]]]=res1[dic[df1.iloc[i,9]],dic[df1.iloc[i,5]]]+1



print(len(df1))
print(res1)
print(sum(res1))
print(res2)
print(sum(res2))

Unnamed: 0                              0
0              2022003C0120220331_10f.wav
1                                 neutral
GT                                neutral
DB                                disgust
sa                               surprise
ra                                  happy
iemo                                angry
Unnamed: 8                            NaN
GT2                              surprise
Unnamed: 10                           NaN
Unnamed: 11                           NaN
Unnamed: 12                           NaN
Unnamed: 13                   false alarm
Name: 0, dtype: object
surprise
surprise
f
419
[[16 13  0  0 13 71  2]
 [ 0 37  0  0  1  4  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  6  0  1  0]
 [ 0  2  0  1 22  1  0]
 [ 0  1  0  1  0 60  0]
 [ 0  0  0  0  0  0  2]]
[ 16  53   0   8  36 137   4]
[[ 3 12  0  0  9 75  2]
 [ 0  2  0  0  0  0  0]
 [ 0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  5  0  0]
 [ 0  0  0  0  2 53  0]
 [ 0  0  0  0  0  0  1

<ipython-input-10-4802a97341bc>:13: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  res1=np.zeros((7,7),dtype=np.int)
<ipython-input-10-4802a97341bc>:14: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for 